// <auto-generated />
using System;
using CarService_MVC.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarService_MVC.Data.Migrations
{
    [DbContext(typeof(AutoSerwisContext))]
    [Migration("20260314140625_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarService_MVC.Data.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Clients__3214EC07DF37C8D2");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CarService_MVC.Data.Models.CmsContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__CmsConte__3214EC0796A0A4EB");

                    b.HasIndex(new[] { "Key" }, "IX_CmsContents_Key");

                    b.HasIndex(new[] { "Section" }, "IX_CmsContents_Section");

                    b.HasIndex(new[] { "Key" }, "UQ__CmsConte__C41E0289FC55CF53")
                        .IsUnique();

                    b.ToTable("CmsContents");
                });

            modelBuilder.Entity("CarService_MVC.Data.Models.ContactRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ResponseNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id")
                        .HasName("PK__ContactR__3214EC0753C03C7E");

                    b.HasIndex(new[] { "IsRead" }, "IX_ContactRequests_IsRead");

                    b.ToTable("ContactRequests");
                });

            modelBuilder.Entity("CarService_MVC.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("HireDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Employee__3214EC0707E021A6");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CarService_MVC.Data.Models.RepairOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("PlannedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__RepairOr__3214EC074B863D26");

                    b.HasIndex(new[] { "ClientId" }, "IX_RepairOrders_ClientId");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_RepairOrders_CreatedAt")
                        .IsDescending();

                    b.HasIndex(new[] { "EmployeeId" }, "IX_RepairOrders_EmployeeId");

                    b.HasIndex(new[] { "Status" }, "IX_RepairOrders_Status");

                    b.HasIndex(new[] { "VehicleId" }, "IX_RepairOrders_VehicleId");

                    b.ToTable("RepairOrders");
                });

            modelBuilder.Entity("CarService_MVC.Data.Models.RepairOrderService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("RepairOrderId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__RepairOr__3214EC07647E8B9C");

                    b.HasIndex(new[] { "RepairOrderId" }, "IX_ROS_RepairOrderId");

                    b.HasIndex(new[] { "ServiceId" }, "IX_ROS_ServiceId");

                    b.ToTable("RepairOrderServices");
                });

            modelBuilder.Entity("CarService_MVC.Data.Models.RepairPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RepairOrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__RepairPh__3214EC072BF9B71C");

                    b.HasIndex("RepairOrderId");

                    b.ToTable("RepairPhotos");
                });

            modelBuilder.Entity("CarService_MVC.Data.Models.RepairStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int>("OldStatus")
                        .HasColumnType("int");

                    b.Property<int>("RepairOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__RepairSt__3214EC07F4019DC8");

                    b.HasIndex(new[] { "RepairOrderId" }, "IX_RSH_RepairOrderId");

                    b.ToTable("RepairStatusHistory", (string)null);
                });

            modelBuilder.Entity("CarService_MVC.Data.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EstimatedDuration")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Services__3214EC078990C1F2");

                    b.HasIndex(new[] { "ServiceCategoryId" }, "IX_Services_CategoryId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("CarService_MVC.Data.Models.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IconCss")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__ServiceC__3214EC073A45C6AC");

                    b.ToTable("ServiceCategories");
                });

            modelBuilder.Entity("CarService_MVC.Data.Models.Testimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Testimon__3214EC078E3EF381");

                    b.ToTable("Testimonials");
                });

            modelBuilder.Entity("CarService_MVC.Data.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Benzyna");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Vin")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)")
                        .HasColumnName("VIN");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Vehicles__3214EC075DF8007E");

                    b.HasIndex(new[] { "ClientId" }, "IX_Vehicles_ClientId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("CarService_MVC.Data.Models.VwActiveRepairOrder", b =>
                {
                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(201)
                        .HasColumnType("nvarchar(201)");

                    b.Property<string>("ClientPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MechanicName")
                        .HasMaxLength(201)
                        .HasColumnType("nvarchar(201)");

                    b.Property<DateTime?>("PlannedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .HasMaxLength(21)
                        .IsUnicode(false)
                        .HasColumnType("varchar(21)");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasMaxLength(201)
                        .HasColumnType("nvarchar(201)");

                    b.ToTable((string)null);

                    b.ToView("vw_ActiveRepairOrders", (string)null);
                });

            modelBuilder.Entity("CarService_MVC.Data.Models.VwRepairOrderSummary", b =>
                {
                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("LineTotal")
                        .HasColumnType("decimal(21, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RepairOrderId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.ToTable((string)null);

                    b.ToView("vw_RepairOrderSummary", (string)null);
                });

            modelBuilder.Entity("CarService_MVC.Data.Models.RepairOrder", b =>
                {
                    b.HasOne("CarService_MVC.Data.Models.Client", "Client")
                        .WithMany("RepairOrders")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("FK_RepairOrders_Clients");

                    b.HasOne("CarService_MVC.Data.Models.Employee", "Employee")
                        .WithMany("RepairOrders")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK_RepairOrders_Employees");

                    b.HasOne("CarService_MVC.Data.Models.Vehicle", "Vehicle")
                        .WithMany("RepairOrders")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK_RepairOrders_Vehicles");

                    b.Navigation("Client");

                    b.Navigation("Employee");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarService_MVC.Data.Models.RepairOrderService", b =>
                {
                    b.HasOne("CarService_MVC.Data.Models.RepairOrder", "RepairOrder")
                        .WithMany("RepairOrderServices")
                        .HasForeignKey("RepairOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ROS_RepairOrders");

                    b.HasOne("CarService_MVC.Data.Models.Service", "Service")
                        .WithMany("RepairOrderServices")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK_ROS_Services");

                    b.Navigation("RepairOrder");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("CarService_MVC.Data.Models.RepairPhoto", b =>
                {
                    b.HasOne("CarService_MVC.Data.Models.RepairOrder", "RepairOrder")
                        .WithMany("RepairPhotos")
                        .HasForeignKey("RepairOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RP_RepairOrders");

                    b.Navigation("RepairOrder");
                });

            modelBuilder.Entity("CarService_MVC.Data.Models.RepairStatusHistory", b =>
                {
                    b.HasOne("CarService_MVC.Data.Models.RepairOrder", "RepairOrder")
                        .WithMany("RepairStatusHistories")
                        .HasForeignKey("RepairOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RSH_RepairOrders");

                    b.Navigation("RepairOrder");
                });

            modelBuilder.Entity("CarService_MVC.Data.Models.Service", b =>
                {
                    b.HasOne("CarService_MVC.Data.Models.ServiceCategory", "ServiceCategory")
                        .WithMany("Services")
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Services_Categories");

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("CarService_MVC.Data.Models.Vehicle", b =>
                {
                    b.HasOne("CarService_MVC.Data.Models.Client", "Client")
                        .WithMany("Vehicles")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Vehicles_Clients");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CarService_MVC.Data.Models.Client", b =>
                {
                    b.Navigation("RepairOrders");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CarService_MVC.Data.Models.Employee", b =>
                {
                    b.Navigation("RepairOrders");
                });

            modelBuilder.Entity("CarService_MVC.Data.Models.RepairOrder", b =>
                {
                    b.Navigation("RepairOrderServices");

                    b.Navigation("RepairPhotos");

                    b.Navigation("RepairStatusHistories");
                });

            modelBuilder.Entity("CarService_MVC.Data.Models.Service", b =>
                {
                    b.Navigation("RepairOrderServices");
                });

            modelBuilder.Entity("CarService_MVC.Data.Models.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("CarService_MVC.Data.Models.Vehicle", b =>
                {
                    b.Navigation("RepairOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
